services:
  mongo:
    image: mongo:7
    container_name: datanadhi-mongo
    ports:
      - "27017:27017"
    networks:
      - datanadhi-net
    volumes:
      - ./data/mongo:/data/db

  postgres:
    image: postgres:16
    container_name: datanadhi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datanadhi_dev
    ports:
      - "5432:5432"
    networks:
      - datanadhi-net
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: datanadhi-redis
    ports:
      - "6379:6379"
    networks:
      - datanadhi-net
    volumes:
      - ./data/redis:/data

  minio:
    image: minio/minio:latest
    container_name: datanadhi-minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - datanadhi-net
    volumes:
      - ./data/minio:/data

networks:
  datanadhi-net:
    external: true
