services:
  mongo:
    image: mongo:7
    container_name: datanadhi-mongo
    ports:
      - "27017:27017"
    networks:
      - datanadhi-net
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: datanadhi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datanadhi_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - datanadhi-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: datanadhi-redis
    ports:
      - "6379:6379"
    networks:
      - datanadhi-net
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: datanadhi-minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - datanadhi-net
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  postgres_data:
  redis_data:
  minio_data:

networks:
  datanadhi-net:
    external: true
